#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Premium Web Scraper Builder v1.0
生成自定义网页抓取脚本 - 无需写代码
输出可直接运行的Python爬虫
"""

import json, sys, os, re
from urllib.request import Request, urlopen
from urllib.error import URLError
from html.parser import HTMLParser

class ScraperBuilder:
    """可视化网页抓取脚本生成器"""
    
    def __init__(self):
        self.output_dir = "generated_scrapers"
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)
    
    def analyze_page(self, url):
        """分析网页结构"""
        req = Request(url, headers={"User-Agent": "Mozilla/5.0"})
        try:
            data = urlopen(req, timeout=10).read().decode('utf-8', errors='ignore')
        except:
            data = urlopen(req, timeout=10).read().decode('utf-8', errors='ignore')
        
        # Detect structure
        has_tables = 'table' in data.lower()
        has_lists = '<ul>' in data.lower() or '<ol>' in data.lower()
        has_articles = 'article' in data.lower()
        has_json_ld = 'application/ld+json' in data
        title_match = re.search(r'<title>(.*?)</title>', data, re.DOTALL)
        title = title_match.group(1).strip() if title_match else url.split('/')[-1]
        
        return {
            "url": url,
            "title": title,
            "has_tables": has_tables,
            "has_lists": has_lists,
            "has_articles": has_articles,
            "has_json_ld": has_json_ld,
            "page_size": len(data)
        }
    
    def generate_scraper(self, url, output_format="csv"):
        """生成抓取脚本"""
        info = self.analyze_page(url)
        
        scraper_code = f'''#!/usr/bin/env python3
# Auto-generated scraper for: {info["title"]}
# Source: {url}
# Generated by Premium Web Scraper Builder

import requests
from bs4 import BeautifulSoup
import json, csv, time, os
from datetime import datetime

URL = "{url}"
OUTPUT_FILE = "{info["title"].replace(' ', '_').lower()}_data.{output_format}"

def fetch_page(url):
    """Fetch page content"""
    headers = {{"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}}
    resp = requests.get(url, headers=headers, timeout=15)
    resp.raise_for_status()
    return resp.text

def parse_data(html):
    """Parse structured data from HTML"""
    soup = BeautifulSoup(html, 'html.parser')
    data = []
    
    # Extract all text content  
    for tag in ['h1', 'h2', 'h3', 'p', 'li', 'td', 'th']:
        for el in soup.find_all(tag):
            text = el.get_text(strip=True)
            if text and len(text) > 5:
                data.append({{"tag": tag, "text": text}})
    
    return data

def save_data(data, fmt):
    """Save scraped data"""
    if fmt == "csv":
        with open(OUTPUT_FILE, 'w', newline='', encoding='utf-8') as f:
            w = csv.writer(f)
            w.writerow(["tag", "text"])
            for item in data:
                w.writerow([item["tag"], item["text"]])
    elif fmt == "json":
        with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
    
    print(f"Saved {{len(data)}} items to {{OUTPUT_FILE}}")

if __name__ == "__main__":
    html = fetch_page(URL)
    data = parse_data(html)
    save_data(data, "{output_format}")
    print(f"Scraper completed at {{datetime.now().isoformat()}}")
'''
        return scraper_code, info
    
    def batch_generate(self, urls, output_format="csv"):
        """批量生成多个抓取脚本"""
        results = []
        for url in urls:
            code, info = self.generate_scraper(url, output_format)
            filename = f"{info['title'].replace(' ', '_').lower()}_scraper.py"
            filepath = os.path.join(self.output_dir, filename)
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(code)
            results.append({"url": url, "file": filepath, "items": info})
        return results


if __name__ == "__main__":
    builder = ScraperBuilder()
    
    if len(sys.argv) > 1:
        url = sys.argv[1]
        fmt = sys.argv[2] if len(sys.argv) > 2 else "csv"
        code, info = builder.generate_scraper(url, fmt)
        filename = f"{info['title'].replace(' ', '_').lower()}_scraper.py"
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(code)
        print(f"Generated: {filename}")
        print(f"URL: {info['url']}")
        print(f"Title: {info['title']}")
    else:
        print("=== Premium Web Scraper Builder ===")
        print("Usage: python scraper_builder.py <url> [csv|json]")
        print()
        print("Demo mode - generating sample scraper...")
        demo_url = "https://example.com"
        code, info = builder.generate_scraper(demo_url)
        print(f"Would generate: scraper for {info['title']}")
        print("Install requirements: pip install requests beautifulsoup4")
